server:
  port: 8123
  servlet:
    context-path: /api
kevinapi:
  client:
    access-key: kevin
    secret-key: abcdefgh
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interface?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root